### ISSUE TITLE
Can't publish reviews anymore

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#830]
Starting today we see these messages when publishing reviews:

![2021-04-28-135346](https://user-images.githubusercontent.com/217543/116399442-374f4700-a829-11eb-9ef5-05511a4177b5.png)

```
Failed to publish: Failed to execute custom review completion condition:

evalmachine.<anonymous>:61 _(file.revisions).reject('obsolete').last().reviewers))
^ TypeError: Cannot read property 'reviewers' of undefined

at _.filter.file (evalmachine.<anonymous>:61:48)
at arrayFilter (/var/task/node_modules/lodash/index.js:1112:21)
at filter (/var/task/node_modules/lodash/index.js:5586:20)
at interceptor (/var/task/node_modules/lodash/index.js:11207:38)
at thru (/var/task/node_modules/lodash/index.js:5218:32)
at baseWrapperValue (/var/task/node_modules/lodash/index.js:2334:38)
at LazyWrapper.lazyValue [as value] (/var/task/node_modules/lodash/index.js:854:24)
at baseWrapperValue (/var/task/node_modules/lodash/index.js:2329:33)
at LodashWrapper.wrapperValue (/var/task/node_modules/lodash/index.js:5406:20) 
```

**Comment by pkaminski** [comment]
This is due to a bug in your custom review completion condition, that unfortunately got copied from one of our earlier sample ones and exacerbated by our recent shift to require reviews of even obsolete file revisions.  I've been fixing these up for folks as I spot the failures but I'm sure I didn't catch them all.  There's instructions on how to fix the bug in [a recent update](https://headwayapp.co/reviewable-changes/reverted-files-in-custom-review-completion-conditions-191987) or if you let me know your repo name I can fix it for you behind the scenes.

**Comment by DamienCassou** [comment]
repo name is `foretagsplatsen/monitor`

**Comment by pkaminski** [comment]
Fixed it!
