### ISSUE TITLE
LGTM approval condition fails with: TypeError: _.keyBy is not a function

### ISSUE THREAD

**Issue by mtlynch** [Reviewable/Reviewable#856]
I'm using the standard "Explicit approval required via a comment" template for approval condition, but it fails with the following error when checking a PR:

```javascript
evalmachine.<anonymous>:25
    const emojis = _.keyBy(sentiment.emojis);
                     ^
  
  TypeError: _.keyBy is not a function
      at evalmachine.<anonymous>:25:20
      at arrayEach (/var/task/node_modules/lodash/index.js:1034:21)
      at Function.<anonymous> (/var/task/node_modules/lodash/index.js:2836:23)
      at evalmachine.<anonymous>:24:3
      at evalmachine.<anonymous>:68:3
      at Script.runInContext (vm.js:144:12)
      at Script.runInNewContext (vm.js:149:17)
      at Object.runInNewContext (vm.js:304:38)
      at Runtime.exports.handler (/var/task/index.js:45:27)
```

I observed this in https://github.com/tiny-pilot/shopify-license-check on PR 4

**Comment by cgiroux86** [comment]
Thanks for the heads up -- issue is resolved.
