### ISSUE TITLE
[BUG] Unable to comment on Review

### ISSUE THREAD

**Issue by ashuser-pendo** [Reviewable/Reviewable#890]
On only one specific review no one is able to add further comments to the review. The review instead throws a JS error:

```
 Failed to publish: Failed to execute custom review completion condition: evalmachine.<anonymous>:77
      _(file.revisions).reject('obsolete').last().reviewers))
                                                 ^
  
  TypeError: Cannot read property 'reviewers' of undefined
      at evalmachine.<anonymous>:77:48
      at arrayFilter (/var/task/node_modules/lodash/index.js:1112:21)
      at filter (/var/task/node_modules/lodash/index.js:5586:20)
      at interceptor (/var/task/node_modules/lodash/index.js:11207:38)
      at thru (/var/task/node_modules/lodash/index.js:5218:32)
      at baseWrapperValue (/var/task/node_modules/lodash/index.js:2334:38)
      at LazyWrapper.lazyValue [as value] (/var/task/node_modules/lodash/index.js:854:24)
      at baseWrapperValue (/var/task/node_modules/lodash/index.js:2329:33)
      at LodashWrapper.wrapperValue (/var/task/node_modules/lodash/index.js:5406:20)
```

We are unable to reproduce this on new Reviews, but this one reviewable is unable to be complete without creating a new one.

Additional details such as specific link to this individual review can be provided privately.

**Comment by ashuser-pendo** [comment]
Closed as this was an internal custom review completion condition we thought we had removed.
